"""
Trading Strategies for Backtesting
"""
from abc import ABC, abstractmethod
import pandas as pd
from dataclasses import dataclass
from typing import Literal

from analysis.indicators import TechnicalAnalysis


@dataclass
class TradeSignal:
    """Signal generated by a strategy"""
    action: Literal["BUY", "SELL", "HOLD"]
    size: float = 1.0  # Position size multiplier
    reason: str = ""


class Strategy(ABC):
    """Base class for trading strategies"""

    name: str = "BaseStrategy"

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        """
        Generate trading signals for each row in data

        Returns:
            Series with values: 1 (BUY), -1 (SELL), 0 (HOLD)
        """
        pass

    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        """Prepare data with necessary indicators"""
        return data


class SMAStrategy(Strategy):
    """Simple Moving Average Crossover Strategy"""

    name = "SMA Crossover"

    def __init__(self, fast_period: int = 20, slow_period: int = 50):
        self.fast_period = fast_period
        self.slow_period = slow_period

    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        ta = TechnicalAnalysis(data)
        ta.add_sma([self.fast_period, self.slow_period])
        return ta.data

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        """
        Buy when fast SMA crosses above slow SMA
        Sell when fast SMA crosses below slow SMA
        """
        fast_col = f"sma_{self.fast_period}"
        slow_col = f"sma_{self.slow_period}"

        signals = pd.Series(0, index=data.index)

        # Calculate crossovers
        fast = data[fast_col]
        slow = data[slow_col]

        # Buy signal: fast crosses above slow
        buy_signal = (fast > slow) & (fast.shift(1) <= slow.shift(1))
        signals[buy_signal] = 1

        # Sell signal: fast crosses below slow
        sell_signal = (fast < slow) & (fast.shift(1) >= slow.shift(1))
        signals[sell_signal] = -1

        return signals


class RSIStrategy(Strategy):
    """RSI Overbought/Oversold Strategy"""

    name = "RSI Strategy"

    def __init__(
        self,
        period: int = 14,
        oversold: float = 30,
        overbought: float = 70
    ):
        self.period = period
        self.oversold = oversold
        self.overbought = overbought

    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        ta = TechnicalAnalysis(data)
        ta.add_rsi(self.period)
        return ta.data

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        """
        Buy when RSI crosses above oversold level
        Sell when RSI crosses below overbought level
        """
        signals = pd.Series(0, index=data.index)
        rsi = data["rsi"]

        # Buy signal: RSI crosses above oversold
        buy_signal = (rsi > self.oversold) & (rsi.shift(1) <= self.oversold)
        signals[buy_signal] = 1

        # Sell signal: RSI crosses below overbought
        sell_signal = (rsi < self.overbought) & (rsi.shift(1) >= self.overbought)
        signals[sell_signal] = -1

        return signals


class MACDStrategy(Strategy):
    """MACD Crossover Strategy"""

    name = "MACD Strategy"

    def __init__(self, fast: int = 12, slow: int = 26, signal: int = 9):
        self.fast = fast
        self.slow = slow
        self.signal_period = signal

    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        ta = TechnicalAnalysis(data)
        ta.add_macd((self.fast, self.slow, self.signal_period))
        return ta.data

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        """
        Buy when MACD crosses above signal line
        Sell when MACD crosses below signal line
        """
        signals = pd.Series(0, index=data.index)

        macd_col = f"MACD_{self.fast}_{self.slow}_{self.signal_period}"
        signal_col = f"MACDs_{self.fast}_{self.slow}_{self.signal_period}"

        macd = data[macd_col]
        signal = data[signal_col]

        # Buy signal: MACD crosses above signal
        buy_signal = (macd > signal) & (macd.shift(1) <= signal.shift(1))
        signals[buy_signal] = 1

        # Sell signal: MACD crosses below signal
        sell_signal = (macd < signal) & (macd.shift(1) >= signal.shift(1))
        signals[sell_signal] = -1

        return signals


class BollingerStrategy(Strategy):
    """Bollinger Band Mean Reversion Strategy"""

    name = "Bollinger Bands"

    def __init__(self, period: int = 20, std: int = 2):
        self.period = period
        self.std = std

    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        ta = TechnicalAnalysis(data)
        ta.add_bollinger_bands((self.period, self.std))
        return ta.data

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        """
        Buy when price touches lower band
        Sell when price touches upper band
        """
        signals = pd.Series(0, index=data.index)

        lower_col = f"BBL_{self.period}_{self.std}"
        upper_col = f"BBU_{self.period}_{self.std}"

        close = data["close"]
        lower = data[lower_col]
        upper = data[upper_col]

        # Buy signal: price at or below lower band
        buy_signal = close <= lower
        signals[buy_signal] = 1

        # Sell signal: price at or above upper band
        sell_signal = close >= upper
        signals[sell_signal] = -1

        return signals


# Available strategies for the UI
AVAILABLE_STRATEGIES = {
    "sma": SMAStrategy,
    "rsi": RSIStrategy,
    "macd": MACDStrategy,
    "bollinger": BollingerStrategy,
}
